version: '3.9'

services:
  app:
    image: fiap-tech-challenge
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    ports:
      - "8009:8009"
    environment:
      - DB_HOST=postgres
    links:
      - db:postgres
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:16.4-bullseye
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: randomP*ssword!
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
