apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db
        image: postgres:16.4-bullseye
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef: 
              name: secrets-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: secrets-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef: 
              name: secrets-config
              key: POSTGRES_DB
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-volume
        emptyDir: {}

