"""empty message

Revision ID: 0a110a4ad43e
Revises: 961151dce78e
Create Date: 2024-10-29 16:02:20.049429

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0a110a4ad43e"
down_revision = "961151dce78e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("customer", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "order",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("order", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_column("order", "created")
    op.add_column(
        "order_items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("order_items", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "product",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("product", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "updated_at")
    op.drop_column("product", "created_at")
    op.drop_column("order_items", "updated_at")
    op.drop_column("order_items", "created_at")
    op.add_column(
        "order", sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.drop_column("order", "updated_at")
    op.drop_column("order", "created_at")
    op.drop_column("customer", "updated_at")
    op.drop_column("customer", "created_at")
    # ### end Alembic commands ###
