"""empty message

Revision ID: 35b917bce0ac
Revises: 0a110a4ad43e
Create Date: 2024-10-29 17:39:17.430089

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35b917bce0ac"
down_revision = "0a110a4ad43e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "status")
    # ### end Alembic commands ###
