"""empty message

Revision ID: a0a0c933128d
Revises: 3778e17f64cb
Create Date: 2025-01-19 18:18:19.929400

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0a0c933128d"
down_revision = "3778e17f64cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("payment_status", sa.String(), nullable=True))
    op.add_column("order", sa.Column("total", sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "total")
    op.drop_column("order", "payment_status")
    # ### end Alembic commands ###
