"""empty message

Revision ID: ebbcf084d585
Revises:
Create Date: 2024-10-17 17:48:44.465927

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ebbcf084d585"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_cpf"), "customer", ["cpf"], unique=False)
    op.create_index(op.f("ix_customer_id"), "customer", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customer_id"), table_name="customer")
    op.drop_index(op.f("ix_customer_cpf"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
